_target_: src.models.vit_classifier_model.ViTClassifierLitModel

feature_extractor_alias: google/vit-base-patch16-224
model_alias: google/vit-base-patch16-224-in21k
num_classes: 8
# n_train_steps = int(len(train_dataset) / config.batch_size * num_epoch)
num_train_steps: 67828 # (43410 / 64) * 100
lr: 0.001
weight_decay: 0.0005
use_scheduler: True
scheduler_num_warmup_steps: 0
# check DatasetOutput for further information
dataset_output: 4
