_target_: src.datamodules.emoreccom_datamodule.EmoRecComDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
modality: 1
text_encoding_max_length: 120
batch_size: 64
train_val_test_split: [ 5112, 500, 500 ]
num_workers: 0
pin_memory: False

